# Este flujo de trabajo construirá un proyecto de iOS usando Xcode
# Para más información, visita: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build and test
      run: xcodebuild -workspace GestionDeInventario.xcworkspace -scheme GestionDeInventario -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' clean build test
